services:
  webssh:
    build: ${ODOO_IMAGES}/webssh
    restart: unless-stopped
    profiles:
      - manual
    labels:
      odoo_framework.apply_env: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${ODOO_IMAGES}/webssh/programs/pgcli:/root/programs/pgcli
  proxy:
    environment:
      WEBSSH_HOST: http://webssh:8080