#manage-order: 12000
version: "3.3"
services:
  cronjobs:
    build: $ODOO_IMAGES/cronjobs
    privileged: true
    restart: 'unless-stopped'
    command: ["daemon"]
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
    volumes:
        - "$ODOO_IMAGES/cronjobs/bin/:/usr/local/bin/:ro"
        - "$HOST_RUN_DIR/cronjobs:/opt/cronjobs"
        - "$DUMPS_PATH:/host/dumps"
        - "$HOST_RUN_DIR:/home/cronworker/.odoo/run/$PROJECT_NAME"
        - ${CUSTOMS_DIR}:/opt/src