# manage-order 100
version: "3"
volumes:
  fluentd_postgres:
    external: false
  fluentd_socket:
    external: false

services:
  fluentd:
    build: $ODOO_IMAGES/logcollector/fluentd
    restart: unless-stopped
    volumes:
      - $ODOO_IMAGES/fluentd/fluentd/conf:/fluentd/etc
      - $ODOO_IMAGES/fluentd/fluentd-configs:/fluentd-configs
      - $HOME/.fluentd.sock.$PROJECT_NAME:/var/run/fluentd.sock
    depends_on:
      - fluentd_postgres
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        compress: "true"
  
  fluentd_cronjobs:
    build: $ODOO_IMAGES/logcollector/cronjobs
    restart: unless-stopped
    depends_on:
      - fluentd_postgres
    environment:
      - POSTGRES_USER=fluentd
      - POSTGRES_PASSWORD=fluentd
      - POSTGRES_DB=fluentd
      - POSTGRES_HOST=fluentd_postgres
      - POSTGRES_PORT=5432
    volumes:
      - $ODOO_IMAGES/logcollector/cronjobs/cronjobs:/cronjobs

  fluentd_postgres:
    image: postgres:16.1
    restart: unless-stopped
    environment:
      - POSTGRES_USER=fluentd
      - POSTGRES_PASSWORD=fluentd
      - POSTGRES_DB=fluentd
    volumes:
      - fluentd_postgres:/var/lib/postgresql/data
      - $ODOO_IMAGES/logcollector/init_sql:/docker-entrypoint-initdb.d
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
        compress: "true"
