# manage-order 1000
services:
    robot:
        build:
            context: $ODOO_IMAGES/robot
        environment:
            OUTPUT_DIR: /opt/output
        volumes:
            - ${CUSTOMS_DIR}/robot_output:/opt/output
            - ${ODOO_IMAGES}/robot/robotest.py:/opt/robot/robotest.py
            - ${ODOO_IMAGES}/robot/keywords:/opt/robot/keywords
            - ${ODOO_IMAGES}/robot/library:/opt/robot/library
