# manage-order 1000
services:
    robot:
        build:
            context: $ODOO_IMAGES/robot
            args:
                OWNER_UID: ${OWNER_UID}
        environment:
            OUTPUT_DIR: /opt/output
            OWNER_UID: ${OWNER_UID}
        volumes:
            - ${HOST_RUN_DIR}/odoo_outdir/robot_output:/opt/output
            - ${ODOO_IMAGES}/robot/robotest.py:/opt/robot/robotest.py
            - ${ODOO_IMAGES}/robot/keywords:/opt/robot/keywords
            - ${ODOO_IMAGES}/robot/library:/opt/robot/library
            - ${CUSTOMS_DIR}:/opt/src
