# manage-order 1000

services:
  odoo_base:
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        #fluentd-address: fluentd:24224
        fluentd-address: unix://$HOME/.fluentd.sock.$PROJECT_NAME/sock
        fluentd-async: 'true'
        #tag: odoo.log.__SERVICE__
        tag: odoo.log