services:
    vscode:
        build: 
          context: $ODOO_IMAGES/vscode
          args:
            OWNER_UID: $OWNER_UID
        cap_add:
          # required by vscode
          - SYS_ADMIN
        restart: "unless-stopped"
        privileged: true
        ports:
            - "5900:5900"
        volumes:
          - ${CUSTOMS_DIR}:/opt/src
          - ${ODOO_IMAGES}/vscode/user_data:/home/userdata
          - ${ODOO_IMAGES}/vscode/entrypoint.sh:/entrypoint.sh
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker:/var/lib/docker
          - "${ODOO_IMAGES}:/home/user1/.odoo/images"
          - "${HOST_RUN_DIR}:/home/user1/.odoo/run/$PROJECT_NAME"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - DISPLAY_WIDTH=${VSCODE_WIDTH}
            - DISPLAY_HEIGHT=${VSCODE_HEIGHT}
            - DISPLAY_COLOR=16
    novnc_vscode:
        build:
          context: $ODOO_IMAGES/novnc
          args:
            relpathname: vscode
        restart: "unless-stopped"
        links:
            - vscode
        environment:
          - DISPLAY_WIDTH=${VSCODE_WIDTH}
          - DISPLAY_HEIGHT=${VSCODE_HEIGHT}
          - AUTOCONNECT=true
          # - RUN_XTERM={yes|no} (yes)
          # - RUN_FLUXBOX={yes|no} (yes)
          - VNC_PASSWORD=code
          - VNC_SERVER=vscode:5900
          - VIEW_ONLY=false