version: "3.3"
services:
  theia_rewriter:
    image: "nginx:1.21"
    volumes:
      - ${ODOO_IMAGES}/theia_odoo_vim_integration/nginx.conf:/etc/nginx/nginx.conf
  theia:
    build:
      context: ${ODOO_IMAGES}/theia_odoo_vim
      args:
        USER_ID: ${OWNER_UID}
        DOCKER_GROUP_ID: ${DOCKER_GROUP_ID}
    privileged: true
    volumes:
      - ${CUSTOMS_DIR}:/home/project
      - ${ODOO_IMAGES}/theia_odoo_vim/add_vsix_files:/home/vsix_files
      - ~/.odoo:/home/theia/.odoo
      - ${ODOO_HOME}:/usr/local/lib/python3.7/dist-packages/wodoo
      - ${ODOO_HOME}/tools/snippets/snippets.vsix:/home/vsix_files/snippets.vsix
      - ${ODOO_IMAGES}/theia_odoo_vim_integration/plugins:/home/plugins
