#manage-order: 5000
services:
  proxy_abstract:
    build: $ODOO_IMAGES/proxy
    restart: unless-stopped
    # ports:
      # - "9228:9228"
      # - "9995:80"
    networks:
      - default
    volumes:
      - $HOST_RUN_DIR/proxy:/etc/proxy
      - $HOST_RUN_DIR/run/intercom:/intercom
      - $ODOO_IMAGES/proxy/app/server.js:/usr/src/app/server.js
      - ${CUSTOMS_DIR}:/usr/src/app/odoo
      - ${HOST_RUN_DIR}/odoo_outdir/robot_output:/robot_output

